### ISSUE TITLE
filter issues by regex

### ISSUE THREAD

**Issue by rakyll** [bradfitz/go-issue-mirror#10]
What I don't appreciate about Github issues is that the search functionality they provide doesn't allow you to filter by prefix. Having a search bar on the top that looks for the string i provide in the title by prefix would be nice to have.

Then, I can search issues belong to certain packages I am interested in by `^pkgname\:`

**Comment by dmitshur** [comment]
Do you get a lot of false positives if you just search for `pkgname: ` (note, it ends with a colon and space) without regexp?

Also, what package(s) does this issue refer to?

**Comment by rakyll** [comment]
Github requires `is:issue is:open "pkgname:" in:title` to search for titles which is pretty verbose and not guaranteed to return packages with pkgname: prefix but anything that contains.

If servegoissue had regex filtering on titles, there would be little motivation for me to use Github anymore :)

**Comment by dmitshur** [comment]
I see what you mean about GitHub search; I agree it's possible to do better (with sufficient work invested).

`servegoissues` itself does not currently implement search at all - it relies on you to use your browser's built-in search. It's viable because all issues are displayed on one page (for now). In [this video](https://www.youtube.com/watch?v=_JN4lMW1dcs) I did a search for username around the 0:32 second mark to give you an idea of what it looks like.

Have you already tried doing a text search in `servegoissues`? You can include the colon and space at the end of pkgname, which you can't do as precisely in GitHub search.

Also, since we're using the browser's search, do you know if there are any extensions that add regexp searching to your browser? If so, you could use that.

When implementing search inside `servegoissues`, I can consider supporting regexp and other more advanced things, but I'd really like to first learn how the current solution works and what kind of problems it has. Then it's easier to work on addressing those issues (by regexp or other ways).

**Comment by rakyll** [comment]
> Also, since we're using the browser's search, do you know if there are any extensions that add regexp searching to your browser? If so, you could use that.

This works well but it is a pretty long list of issues and much visual distraction. I'd rather the page was filtering stuff I want to focus on.

> but I'd really like to first learn how the current solution works

This makes sense. I am going to close this issue for a while. If I have time, I can experiment with the idea on my fork.

**Comment by dmitshur** [comment]
> This works well but it is a pretty long list of issues and much visual distraction. I'd rather the page was filtering stuff I want to focus on.

Makes sense. I like to defer working on things that have higher implementation/maintenance cost and are less critical/useful (in favor of things that are more irreplaceable). But that sounds like it could be one of useful next features to work on. Thanks for providing the feedback.

> This makes sense. I am going to close this issue for a while. If I have time, I can experiment with the idea on my fork.

👍

If possible, keep me posted, and let me know if the code's on GitHub or somewhere I can follow/watch it for updates (I'm also happy to answer any questions about it!).

**Comment by rakyll** [comment]
Sure, I will update you if I get anything done.
