### ISSUE TITLE
cmd/servegoissues: build is broken

### ISSUE THREAD

**Issue by rakyll** [bradfitz/go-issue-mirror#8]
```
$ go get github.com/bradfitz/go-issue-mirror/cmd/servegoissues
package github.com/shurcooL/go/gists/gist6418290: cannot find package "github.com/shurcooL/go/gists/gist6418290" in any of:
    /Users/jbd/go/src/github.com/shurcooL/go/gists/gist6418290 (from $GOROOT)
    /Users/jbd/src/github.com/shurcooL/go/gists/gist6418290 (from $GOPATH)
package github.com/shurcooL/go/gists/gist6418462: cannot find package "github.com/shurcooL/go/gists/gist6418462" in any of:
    /Users/jbd/go/src/github.com/shurcooL/go/gists/gist6418462 (from $GOROOT)
    /Users/jbd/src/github.com/shurcooL/go/gists/gist6418462 (from $GOPATH)
```

/cc @shurcooL

**Comment by bradfitz** [comment]
Depending on gists!?!? That's disgusting.

**Comment by dmitshur** [comment]
Brad, please merge #6, it fixes the build.

Burcu, please use `go get -u github.com/bradfitz/go-issue-mirror/cmd/servegoissues` as the README says. I see you missed the `-u` flag, it's very important. :)

**Comment by dmitshur** [comment]
> Depending on gists!?!? That's disgusting.

I agree. That's why I worked really hard and refactored all my code to get rid of them 5 months ago. Commit https://github.com/shurcooL/go/commit/1ab69ca4f77382ac0529be9cf93df0502236e817 marked the milestone of 🔥ing the very last gist package.

Please rest assured none of my packages import gists anymore, at least not on my computer and not upstream. If you have outdated dependencies, as was the case for @rakyll, then I can't do much about that except to suggest using `go get` with `-u` flag. If you want to easily see updates for the Go packages in your GOPATH, I recommend [Go Package Store](https://github.com/shurcooL/Go-Package-Store#readme) (which also doesn't use any gists... because they don't exist anymore! only their ghosts do... 😞).
