### ISSUE TITLE
cmd/servegoissues: add a link to the original issue

### ISSUE THREAD

**Issue by rakyll** [bradfitz/go-issue-mirror#9]
I want to comment on the issue when I have Internet and a link to the original thread would be awesome to have.

I also don't understand the functionality of the commenting button under each issue. It doesn't work at all. Remove and replace with a link to the original issue?

**Comment by dmitshur** [comment]
Is this an issue for `github.com/bradfitz/go-issue-mirror/cmd/servegoissues` package (the GUI) or `github.com/bradfitz/go-issue-mirror/issues` package (the CLI)?

**Comment by rakyll** [comment]
For the GUI served from cmd/servegoissues.

**Comment by dmitshur** [comment]
Thanks, that clears it up.

> I also don't understand the functionality of the commenting button under each issue. It doesn't work at all.

I see you're referring to this:

![image](https://cloud.githubusercontent.com/assets/1924134/18031938/012c6ec4-6caa-11e6-8f24-8c2a0dfc869b.png)

`servegoissues` uses issuesapp package with a custom [view-only `issues.Service` implementation](https://github.com/bradfitz/go-issue-mirror/blob/db2e0490fc881fc91802db486039ebe718927ffa/cmd/servegoissues/servegoissues.go#L253-L271) to display issues. That [issuesapp package](https://github.com/shurcooL/issuesapp#readme) is typically meant for both viewing and creating/editing issues. The "Sign in via GitHub" prompt appears in place of a real "new comment" box when there's no user logged in, because it's not possible to post comments without being logged in.

> Remove and replace with a link to the original issue?

That makes a lot of sense to me. I'll make a PR that implements that.
